###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:


    mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: default

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql
      ports:
        - 8080:80
      environment:
        PMA_HOST: mysql
